mistral-orpo-mix:
  prompt_template: "mistral-orpo-mix/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "alvarobartt/mistral-orpo-mix"
    model_kwargs:
      torch_dtype: "bfloat16"
    max_new_tokens: 2048
    temperature: 0.7
    do_sample: True
  pretty_name: "Mistral-ORPO-Mix"
  link: "https://huggingface.co/alvarobartt/mistral-orpo-mix"